export const ADD_SELECT_LIST = 'ADD_TODO';

export const FETCH_SELECT_LIST_BEGIN   = 'FETCH_SELECT_LIST_BEGIN';
export const FETCH_SELECT_LIST_SUCCESS = 'FETCH_SELECT_LIST_SUCCESS';
export const FETCH_SELECT_LIST_FAILURE = 'FETCH_SELECT_LIST_FAILURE';

