export const ADD_SELECT_LIST = 'ADD_SELECT_LIST';

export const ACTIVE_SELECT = 'ACTIVE_SELECT';

export const FETCH_RENDER_CONTENT_SUCCESS = 'FETCH_RENDER_CONTENT_SUCCESS';

export const FETCH_SELECT_LIST_BEGIN   = 'FETCH_SELECT_LIST_BEGIN';
export const FETCH_SELECT_LIST_SUCCESS = 'FETCH_SELECT_LIST_SUCCESS';
export const FETCH_SELECT_LIST_FAILURE = 'FETCH_SELECT_LIST_FAILURE';

